spring.application.name=speakly
spring.flyway.locations=classpath:db/migration
spring.datasource.url=jdbc:mariadb://localhost:3306/speakly?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
server.port=8080
cloudinary.cloud-name=placeholder
cloudinary.api-key=placeholder
cloudinary.api-secret=placeholder
bank.api.base-url=http://localhost:8081
bank.api.username=placeholder
bank.api.key=placeholder
bank.api.destination-iban=placeholder
